language: node_js
branches:
  only:
    - master
    - dev
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - yarn
  - yarn lint
  - yarn build
notifications:
  slack:
    secure: AlGJ8Jk5RBr6V9eXMWahbX/0QRWsS9lcWwtYI+Ic3xFrI4NcT1i9kJklZycdamW0OgcFuR1EFgIyWBE5bH1nRce+qxriC55qNidIQPowcYIaPyC1H/vdzNzLQm0n/j2Q+J2mmY9wtVqr3PxdbPluKQmHdpfHueo+Heo5gDOpxpYWJpfs+F4w+qZP7xeBXW1g8oRUy1oA53jGLv0n2YqOhToztJ80X993dzrrhMmSHqR/Ao6NTyEEnoV+d+F3nK66coiWe2kRSZ3S5FGumnUnZJ7hAcjozYI2odiprP/iAV6j41WcbYpjrgfsouVC+su1cOYuNr0kekz7LgEZE/6MlSpjvZp3MPbXzO7xjuvPClE45hRvmJX7c2zMX3p5SurYTELdOsxucZ0q0yGBKKBd0uwL7I91+zo0g9uCulZHRe4kd2NZwmvh7TRa4qpHofV1KKR1OcGB0cW5y5WnS2TfiyGAwuwcFYnb5AwiFNXP6/9bcTUI+C/ryMzAhVPXk1tkJwLWMJ9ew4c0gMKdRcXxMpeqSD6DDTFNkWaMTC80UJXrE4c/kLRFV/PfGb0kgzoK5MgkDdeNIVLrshMgTANNjfMsAUcmsSa+8mwvmt13JZfdLBGf8w2oC97a+/wAv0pUMTV4SguuXaSM2ENsR739a6KBwmgu9Kwjk1du8CQfPGM=
deploy:
  - provider: openshift
    server: $OPENSHIFT_SERVER
    project: ua
    app: front-bouffe
    token: $OPENSHIFT_TOKEN
    on:
      branch: master
    edge: true
